-- =============================================================================
-- Database Schema for: <!-- App Name -->
-- Generated by: migrate-filemaker Phase 4
-- Source: FileMaker DDR specs
-- Target: <!-- PostgreSQL / MySQL / SQLite -->
-- =============================================================================

-- GENERATION INSTRUCTIONS (for the AI generating this file):
--
-- 1. Read `ddr/specs/01_tables.json` — only create tables for entries with schema
--    fields (skip globals-only tables).
--
-- 2. For each table:
--    a. Convert table name to lowercase snake_case plural
--    b. Add `id SERIAL PRIMARY KEY` (or UUID if recommended)
--    c. Convert each schema field using the type mapping from
--       reference/schema-translation-guide.md
--    d. Add `created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`
--    e. Add `updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`
--    f. Add NOT NULL for fields with "not empty" validation
--    g. Add UNIQUE for fields with "unique value" validation
--    h. Add CHECK constraints for fields with range validation
--
-- 3. Read `ddr/specs/03_relationships.json` — create foreign keys:
--    a. Only for equi-join relationships (operator "=")
--    b. Add ON DELETE CASCADE if relationship has "delete_related"
--    c. Add ON DELETE SET NULL for optional relationships
--    d. Skip inequality/Cartesian joins (these become queries, not constraints)
--
-- 4. Read `ddr/specs/06_value_lists.json` — for custom value lists:
--    a. Create ENUM types for short stable lists
--    b. Create reference tables for user-managed or long lists
--
-- 5. Create indexes for:
--    a. All foreign key columns
--    b. Fields used in FM find operations (check scripts for Enter Find Mode)
--    c. Fields with unique validation
--    d. Common sort fields
--
-- 6. Add comments for:
--    a. Calculated fields that become app logic (note the original calculation)
--    b. Globals-only tables that become application config
--    c. Any non-obvious type conversions
--
-- 7. Order tables by dependency (referenced tables before referencing tables)

-- =============================================================================
-- ENUMS / TYPES
-- =============================================================================

-- From value list: <!-- ValueListName -->
-- CREATE TYPE <!-- type_name --> AS ENUM (<!-- 'Value1', 'Value2', ... -->);

-- =============================================================================
-- REFERENCE TABLES (for dynamic value lists)
-- =============================================================================

-- From value list: <!-- ValueListName -->
-- CREATE TABLE <!-- table_name --> (
--   id          SERIAL PRIMARY KEY,
--   name        VARCHAR(100) NOT NULL UNIQUE,
--   sort_order  INTEGER NOT NULL DEFAULT 0
-- );

-- =============================================================================
-- CORE TABLES
-- =============================================================================

-- Source: FM table "<!-- OriginalTableName -->" (<!-- n --> records, <!-- n --> schema fields)
-- CREATE TABLE <!-- table_name --> (
--   id          SERIAL PRIMARY KEY,
--   <!-- columns derived from schema fields -->
--   created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
--   updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
-- );

-- =============================================================================
-- FOREIGN KEYS
-- =============================================================================

-- Source: FM relationship "<!-- RelationshipDescription -->"
-- ALTER TABLE <!-- child_table -->
--   ADD CONSTRAINT fk_<!-- child_table -->_<!-- parent_table -->
--   FOREIGN KEY (<!-- column -->)
--   REFERENCES <!-- parent_table -->(id)
--   ON DELETE <!-- CASCADE / SET NULL / RESTRICT -->;

-- =============================================================================
-- INDEXES
-- =============================================================================

-- Foreign key indexes
-- CREATE INDEX idx_<!-- table -->_<!-- column --> ON <!-- table -->(<!-- column -->);

-- Search/filter indexes (from FM script find operations)
-- CREATE INDEX idx_<!-- table -->_<!-- column --> ON <!-- table -->(<!-- column -->);

-- =============================================================================
-- UPDATE TRIGGER (for updated_at)
-- =============================================================================

-- PostgreSQL: Create a trigger function for auto-updating updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply to each table:
-- CREATE TRIGGER set_updated_at
--   BEFORE UPDATE ON <!-- table_name -->
--   FOR EACH ROW
--   EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- NOTES
-- =============================================================================

-- Globals-only tables (not migrated as database tables):
-- - <!-- TableName -->: <!-- purpose, e.g., "App preferences — move to config" -->

-- Calculated fields (not database columns — implement in application):
-- - <!-- TableName.FieldName -->: <!-- original FM calculation -->

-- Summary fields (implement as SQL queries):
-- - <!-- TableName.FieldName -->: <!-- e.g., "SUM of LineItems::Amount" -->
